### ISSUE TITLE
⇔ should return only unique combinations

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [aaronpeikert/StenoGraphs.jl#28]
Current behaviour is:

```julia
graph = @StenoGraph begin
    [x1, x2, x3] ⇔ [x1, x2, x3]
end

x1 ↔ x1
x1 ↔ x2
x1 ↔ x3
x2 ↔ x1
x2 ↔ x2
x2 ↔ x3
x3 ↔ x1
x3 ↔ x2
x3 ↔ x3
```

Which adds every undirected edge between differing variables twice. This prevents me from specifying saturated models this way. I think it should be

```julia
graph = @StenoGraph begin
    [x1, x2, x3] ⇔ [x1, x2, x3]
end

x1 ↔ x1
x1 ↔ x2
x1 ↔ x3
x2 ↔ x2
x2 ↔ x3
x3 ↔ x3
```

**Comment by Maximilian-Stefan-Ernst** [comment]
I think this is a more general about the behavior of different arrow types. From the OpenMx documentation:

> ‘connect’ has five possible connection types: "single", "all.pairs", "all.bivariate", "unique.pairs",
> "unique.bivariate". The default value is "single". Assuming the values c(‘a’,‘b’,‘c’) for the ‘to’ and
> ‘from’ fields the paths produced by each connection type are as follows:
> "all.pairs": (a,a), (a,b), (a,c), (b,a), (b,b), (b,c), (c,a), (c,b), (c,c).
> "unique.pairs": (a,a), (a,b), (a,c), (b,b), (b,c), (c,c).
> "all.bivariate": (a,b), (a,c), (b,a), (b,c), (c,a), (c,b).
> "unique.bivariate": (a,b), (a,c), (b,c).
> "single": (a,a), (b,b), (c,c).

↔ Behaves like single, which is good I think. But for variances/covariances, for ⇔ a behavior like unique.pairs would be more usefull to have I think. For directed edges, the case is different. ⇒ should behave like "all.pairs", I think this is also intuitive. The reason is simply that `a ↔ b` and `b ↔ a` are the same thing, while `a → b` and `b → a` are not.

**Comment by Maximilian-Stefan-Ernst** [comment]
I dont know if doing this at the end is the best solution. Because you probably would like to warn the user about duplicated edges when building the graph at the end. Consider

```julia
graph = @StenoGraph begin
    x1 ↔ x1
    x1 ↔ x1
end
```
probably should result in a warning about duplicated edges, but 

```julia
graph = @StenoGraph begin
    [x1, x2, x3] ⇔ [x1, x2, x3]
end
```
should not.

**Comment by aaronpeikert** [comment]
```julia
graph = @StenoGraph begin
    x1 ↔ x1
    x1 ↔ x1
end
```

I don't think we need to warn users in this case, since they are building a graph and a graph can not have the same edge twice (an list of edges might, but not a graph, which is confusing since our graph is a list of edges).

More interesting is the intended behavior here:

```julia
graph = @StenoGraph begin
    x1 ↔ label("first")*x1
    x1 ↔ label("second")*x1
end
```

and here

```julia
graph = @StenoGraph begin
    x1 ↔ label("first")*x1
    x1 ↔ weight(3.0)*x1
end
```
Most consistent is probably fusing edges, meaning edges get combined (in case of identical edges they simply are deduplicated) and in case of modified edges probably fusing of modifiers where last modifier overwrites first in case of any clash. 

I think I will consider edges the same based on `hash(typeof(edge), typeof(edge.src), typeof(edge.dst), edge.src.node, edge.dst.node)` and will fuse these. If this is expected, reliable, and consistent behavior of graph construction no warning is required.

**Comment by Maximilian-Stefan-Ernst** [comment]
> ```julia
> graph = @StenoGraph begin
>     x1 ↔ x1
>     x1 ↔ x1
> end
> ```
> 
> I don't think we need to warn users in this case, since they are building a graph and a graph can not have the same edge twice (an list of edges might, but not a graph, which is confusing since our graph is a list of edges).

I think the chance is 99% in this case that it is a copy-paste error and the user wanted to write
```julia
graph = @StenoGraph begin
    x1 ↔ x1
    x2 ↔ x2
end
```
So I think a warning would be very helpful here.

> More interesting is the intended behavior here:
> 
> ```julia
> graph = @StenoGraph begin
>     x1 ↔ label("first")*x1
>     x1 ↔ label("second")*x1
> end
> ```
> 
> and here
> 
> ```julia
> graph = @StenoGraph begin
>     x1 ↔ label("first")*x1
>     x1 ↔ weight(3.0)*x1
> end
> ```
> 
> Most consistent is probably fusing edges, meaning edges get combined (in case of identical edges they simply are deduplicated) and in case of modified edges probably fusing of modifiers where last modifier overwrites first in case of any clash.
I am very much against that. I dont see any use cases: why would you want to overwrite an existing identifier by adding it later again to the same egde? And even if there was a use case, I think 90% of the time this happens it is a copy-paste error and 10% it is intended by the user. So I would raise an error in both cases. There seems nothing wrong with
```julia
graph = @StenoGraph begin
    x1 ↔ label("second")*x1
end
```
and
```julia
graph = @StenoGraph begin
    x1 ↔ label("first")*weight(3.0)*x1
end
```

**Comment by Maximilian-Stefan-Ernst** [comment]
Okay, I take it back. There is a use case for fusing edges with *different* modifiers. Maybe you prefer the following Syntax):
```julia
graph = @StenoGraph begin
   # labels
    x1 ↔ label("first")*x1 + label("second")*x2
   # weights
    x1 ↔ weight(3.0)*x1 + weight(2.0)*x2
end
```
over

graph = @StenoGraph begin
    x1 ↔ label("first")*weight(3.0)*x1 + label("second")*weight(2.0)*x2
end
```

**Comment by aaronpeikert** [comment]
I disagree because of two points.

1. Modifiers are stored in dicts, writing in a Dict with the same key replaces the element. See documentation here:

https://aaronpeikert.github.io/StenoGraphs.jl/dev/man/types/#StenoGraphs.ModifiedNode

2. I find this behavior useful, consider the case where you as a user set many modifier at once programmatically but want some exceptions. I find it natural do simply overwrite exceptions later like here:

```julia
using StenoGraphs

struct fixed <: EdgeModifier f end
items = Node.([:a, :b, :c])

@StenoGraph begin
   latent → _(items) .* Ref(fixed(_(missing)))
   latent → fixed(1.0) * :a
end
```

**Comment by aaronpeikert** [comment]
So `unique()` is already informed about:
> The reason is simply that `a ↔ b` and `b ↔ a` are the same thing, while `a → b` and `b → a` are not.

In other words StenoGraph know that:

```julia
g = @StenoGraph begin
    a ↔ b * fixed(1.0)
    b ↔ a * fixed(1.0)
end

g[2] == g[1]
```

So I phrased that badly:

> I think I will consider edges the same based on hash(typeof(edge), typeof(edge.src), typeof(edge.dst), edge.src.node, edge.dst.node)

What I meant is `hash(typeof(edge), typeof(edge.src), typeof(edge.dst), edge.src.node, edge.dst.node)` could form an ID of sorts, that this means the same edge but it is of course not the same object.

**Comment by Maximilian-Stefan-Ernst** [comment]
Okay, so I will try to use `unique()` and see if that works.

I don't think it matters what the default behavior of a dict is, however I think the use case is convincing and nice to have. But I think overwriting a modifier that way should still give a warning. Also generating the same edge twice without modifiers should give a warning, I think. There are just too many copy/paste errors etc. that would be caught by this.

**Comment by Maximilian-Stefan-Ernst** [comment]
`unique()` works for our example model tests.
